POST http://localhost:5650/api/contacts
Content-Type: application/json

//In case you forgot what properties to pass you can check your DTO
//"interface" to view them

{
  "owner": 1,
  "firstname": "don",
  "lastname": "Green",
  "birthdate": "2022-02-05",
  "relation": "Self",
  "notes": "none needed"
}

####
#GET http://localhost:5650/api/contacts
#
####

  public Long owner ;

    public String firstname;

    public String lastname;

    public Date birthdate;

    public String relation;

    public String notes;